import { BarChart3, FlaskConical, Type, MessageSquare, Hash, Timer, PlusCircle, Minus, AtSign, Bold, Calendar } from 'lucide-react';
import { LINKEDIN_LIMITS } from '../lib/postCompiler';

// ============================================
// TRANSLATIONS
// ============================================
export const translations = {
  en: {
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      login: 'Sign In',
      startFree: 'Start Free',
      logout: 'Sign Out',
      admin: 'Admin',
      editor: 'Editor',
      back: 'Back',
    },
    // Landing Page
    landing: {
      badge: 'For Ambitious Founders',
      headline1: 'Validate your',
      headline2: 'Market-Fit in 48h',
      subheadline: 'Precise market data through LinkedIn surveys.',
      subheadline2: ' Fast. Data-driven. Effective.',
      ctaButton: 'Start Validation',
      stat1Value: '48h',
      stat1Label: 'Time to Insights',
      stat2Value: '10x',
      stat2Label: 'Faster than Interviews',
      stat3Value: '100%',
      stat3Label: 'Data-Driven',
      whyTitle: 'Why Breaking Dynamics?',
      whySubtitle: 'Three reasons why founders choose us',
      feature1Title: 'Lightning Fast',
      feature1Desc: 'Market data in 48 hours instead of weeks. Time is your most valuable asset.',
      feature2Title: 'Precise',
      feature2Desc: 'Real feedback from real decision-makers. No guesses, only facts.',
      feature3Title: 'Scalable',
      feature3Desc: 'From idea to product-market-fit. Content + insights in one.',
      communityBadge: 'Community',
      communityTitle: 'Join the',
      communityTitle2: 'Founder Community',
      communityDesc: 'Exclusive insights, beta access & direct exchange with other founders.',
      communityButton: 'Join Community',
      privacy: 'Privacy',
      terms: 'Terms',
    },
    // Auth
    auth: {
      login: 'Sign In',
      register: 'Sign Up',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      or: 'or',
      createAccount: 'Create new account',
      alreadyRegistered: 'Already registered? Sign In',
      privacyConsent: 'I agree to the privacy policy.',
      emailExists: 'This email is already registered. Please sign in.',
      wrongCredentials: 'Email or password incorrect',
      passwordMinLength: 'Password must be at least 6 characters',
      passwordMismatch: 'Passwords do not match',
      loginFailed: 'Login failed',
      registerFailed: 'Registration failed',
    },
    // Dashboard
    dashboard: {
      home: 'Dashboard',
      history: 'History',
      analysis: 'Analysis',
      newValidation: 'New Validation',
      totalTests: 'Total Tests',
      thisWeek: 'This Week',
      testProgress: 'Test Progress',
      week: 'Week',
      months: 'Months',
      years: 'Years',
      noData: 'No data yet',
      lastTests: 'Recent Tests',
      validationsTotal: 'validations total',
      noSurveys: 'No Surveys',
      createFirst: 'Create your first validation!',
      title: 'Title',
      hypothesis: 'Hypothesis',
      created: 'Created',
      actions: 'Actions',
      loadError: 'Loading error:',
      retry: 'Retry',
      comingSoon: 'Coming soon...',
      inDevelopment: 'In Development',
      deleteSurvey: 'Really delete survey?',
      deleted: 'Survey deleted',
      deleteFailed: 'Delete failed:',
    },
    // Editor
    editor: {
      blocks: 'Blocks',
      preview: 'Preview',
      required: 'Required',
      internal: 'Internal',
      dropHere: 'Drop block here or drag from sidebar',
      createButton: 'Create',
      saving: 'Saving...',
      cancel: 'Cancel',
      toHome: 'To Home',
      done: 'Done!',
      postReady: 'Your post is ready',
      copyText: 'Copy Text',
      copied: 'Copied!',
      newSurvey: 'New Survey',
      saveData: 'Save Data?',
      copyOnly: 'Copy only',
      copyAndEmail: 'Copy + Get Email',
      sendingEmail: 'Sending survey...',
      emailSent: 'Survey sent to your email!',
      emailFailed: 'Survey created! (Email could not be sent)',
      postTitle: 'Post title...',
      hypothesisQuestion: 'Hypothesis question...',
      option: 'Option',
      challengeInfo: 'This content will NOT be published in the LinkedIn post. It serves as internal documentation of your validation hypothesis.',
      challengePlaceholder: 'Describe your problem or hypothesis that you want to validate...\n\nExample: We believe that B2B SaaS founders have difficulty getting quick market feedback.',
      emailAddress: 'Email address',
      saveFailed: 'Save failed: ',
      surveyUpdated: 'Survey updated!',
      surveyCreated: 'Survey created!',
      ctaPlaceholder: "e.g. Comment 'PDF'",
      hashtagPlaceholder: '#Startup #MVP',
      customText: 'Custom text...',
      mentionPlaceholder: '@JohnDoe',
      numberPlaceholder: '87% of founders...',
      duration1day: '24H',
      duration3days: '3 DAYS',
      duration1week: '1 WEEK',
      durationLabel: 'Duration',
      dateLabel: 'Date',
      timeLabel: 'Time',
      survey: 'Survey',
      acceptPrivacy: 'Please accept privacy policy',
      emailAlreadyRegistered: 'This email is already registered. Please sign in.',
      charCount: 'characters',
      linkedInLimit: 'LinkedIn Limit',
      shareToLinkedIn: 'Share to LinkedIn',
      copiedForLinkedIn: 'Text copied! LinkedIn is opening...',
      pollInstructions: 'Add your poll on LinkedIn:',
      pollStep1: 'Paste the copied text into the post',
      pollStep2: 'Click the "Poll" icon (bar chart) in the toolbar',
      pollStep3: 'Add your poll question and options',
    },
    // Blocks
    blocks: {
      POLL: 'Poll Core',
      CHALLENGE: 'Validation Challenge',
      TITLE: 'Post Title',
      CTA: 'Call-to-Action',
      HASHTAG: 'Hashtags',
      DURATION: 'Duration',
      CUSTOM: 'Custom Text',
      DIVIDER: 'Divider',
      MENTION: '@Mention',
      NUMBER: 'Numbers',
      SCHEDULE: 'Schedule',
    },
    // Feedback
    feedback: {
      title: 'Feedback',
      bugReport: 'Report Bug',
      idea: 'Idea',
      describeBug: 'Describe the bug...',
      describeIdea: 'Describe your idea...',
      emailOptional: 'Email (optional, for follow-up)',
      submit: 'Submit',
      thanks: 'Thanks for your feedback!',
      willContact: 'We will get back to you.',
      sent: 'Feedback sent!',
      sendFailed: 'Feedback could not be sent',
    },
    // Common
    common: {
      textCopied: 'Text copied!',
      loading: 'Loading...',
    },
    // Warnings
    warnings: {
      postTooLong: 'Post exceeds LinkedIn limit',
      pollQuestionTooLong: 'Poll question too long',
      pollOptionTooLong: 'Poll option too long',
    },
  },
  de: {
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      login: 'Anmelden',
      startFree: 'Kostenlos starten',
      logout: 'Abmelden',
      admin: 'Admin',
      editor: 'Editor',
      back: 'Zurück',
    },
    // Landing Page
    landing: {
      badge: 'Für ambitionierte Gründer',
      headline1: 'Validiere deinen',
      headline2: 'Market-Fit in 48h',
      subheadline: 'Präzise Marktdaten durch LinkedIn-Umfragen.',
      subheadline2: ' Schnell. Datengetrieben. Effektiv.',
      ctaButton: 'Validierung starten',
      stat1Value: '48h',
      stat1Label: 'Time to Insights',
      stat2Value: '10x',
      stat2Label: 'Schneller als Interviews',
      stat3Value: '100%',
      stat3Label: 'Datengetrieben',
      whyTitle: 'Warum Breaking Dynamics?',
      whySubtitle: 'Drei Gründe, warum Gründer auf uns setzen',
      feature1Title: 'Blitzschnell',
      feature1Desc: 'Marktdaten in 48 Stunden statt Wochen. Zeit ist dein wertvollstes Asset.',
      feature2Title: 'Präzise',
      feature2Desc: 'Echtes Feedback von echten Entscheidern. Keine Vermutungen, nur Fakten.',
      feature3Title: 'Skalierbar',
      feature3Desc: 'Von der Idee zum Product-Market-Fit. Content + Insights in einem.',
      communityBadge: 'Community',
      communityTitle: 'Werde Teil der',
      communityTitle2: 'Gründer-Community',
      communityDesc: 'Exklusive Insights, Beta-Zugang & direkter Austausch mit anderen Gründern.',
      communityButton: 'Community beitreten',
      privacy: 'Datenschutz',
      terms: 'AGB',
    },
    // Auth
    auth: {
      login: 'Anmelden',
      register: 'Registrieren',
      email: 'E-Mail',
      password: 'Passwort',
      confirmPassword: 'Passwort bestätigen',
      or: 'oder',
      createAccount: 'Neues Konto erstellen',
      alreadyRegistered: 'Bereits registriert? Anmelden',
      privacyConsent: 'Ich stimme den Datenschutzbestimmungen zu.',
      emailExists: 'Diese E-Mail ist bereits registriert. Bitte melde dich an.',
      wrongCredentials: 'E-Mail oder Passwort falsch',
      passwordMinLength: 'Passwort muss mindestens 6 Zeichen haben',
      passwordMismatch: 'Passwörter stimmen nicht überein',
      loginFailed: 'Anmeldung fehlgeschlagen',
      registerFailed: 'Registrierung fehlgeschlagen',
    },
    // Dashboard
    dashboard: {
      home: 'Dashboard',
      history: 'Historie',
      analysis: 'Analyse',
      newValidation: 'Neue Validierung',
      totalTests: 'Gesamt Tests',
      thisWeek: 'Diese Woche',
      testProgress: 'Test-Verlauf',
      week: 'Woche',
      months: 'Monate',
      years: 'Jahre',
      noData: 'Noch keine Daten',
      lastTests: 'Letzte Tests',
      validationsTotal: 'Validierungen insgesamt',
      noSurveys: 'Keine Umfragen',
      createFirst: 'Erstelle deine erste Validierung!',
      title: 'Titel',
      hypothesis: 'Hypothese',
      created: 'Erstellt',
      actions: 'Aktionen',
      loadError: 'Fehler beim Laden:',
      retry: 'Erneut versuchen',
      comingSoon: 'Kommt bald...',
      inDevelopment: 'In Entwicklung',
      deleteSurvey: 'Umfrage wirklich löschen?',
      deleted: 'Umfrage gelöscht',
      deleteFailed: 'Löschen fehlgeschlagen:',
    },
    // Editor
    editor: {
      blocks: 'Bausteine',
      preview: 'Vorschau',
      required: 'Pflicht',
      internal: 'Intern',
      dropHere: 'Baustein hier ablegen oder aus der Sidebar ziehen',
      createButton: 'Erstellen',
      saving: 'Speichern...',
      cancel: 'Abbrechen',
      toHome: 'Zur Startseite',
      done: 'Fertig!',
      postReady: 'Dein Post ist bereit',
      copyText: 'Text kopieren',
      copied: 'Kopiert!',
      newSurvey: 'Neue Umfrage',
      saveData: 'Daten sichern?',
      copyOnly: 'Nur kopieren',
      copyAndEmail: 'Kopieren + E-Mail erhalten',
      sendingEmail: 'Survey wird gesendet...',
      emailSent: 'Survey wurde an deine E-Mail gesendet!',
      emailFailed: 'Survey erstellt! (E-Mail konnte nicht gesendet werden)',
      postTitle: 'Post-Titel...',
      hypothesisQuestion: 'Hypothesen-Frage...',
      option: 'Option',
      challengeInfo: 'Dieser Inhalt wird NICHT im LinkedIn-Post veröffentlicht. Er dient der internen Dokumentation deiner Validierungs-Hypothese.',
      challengePlaceholder: 'Beschreibe dein Problem oder deine Hypothese, die du validieren möchtest...\n\nBeispiel: Wir glauben, dass B2B-SaaS-Gründer Schwierigkeiten haben, schnelles Marktfeedback zu erhalten.',
      emailAddress: 'E-Mail-Adresse',
      saveFailed: 'Speichern fehlgeschlagen: ',
      surveyUpdated: 'Umfrage aktualisiert!',
      surveyCreated: 'Umfrage erstellt!',
      ctaPlaceholder: "z.B. Kommentiere 'PDF'",
      hashtagPlaceholder: '#Startup #MVP',
      customText: 'Eigener Text...',
      mentionPlaceholder: '@MaxMuster',
      numberPlaceholder: '87% der Gründer...',
      duration1day: '24H',
      duration3days: '3 TAGE',
      duration1week: '1 WOCHE',
      durationLabel: 'Laufzeit',
      dateLabel: 'Datum',
      timeLabel: 'Uhrzeit',
      survey: 'Umfrage',
      acceptPrivacy: 'Bitte Datenschutz akzeptieren',
      emailAlreadyRegistered: 'Diese E-Mail ist bereits registriert. Bitte melde dich an.',
      charCount: 'Zeichen',
      linkedInLimit: 'LinkedIn Limit',
      shareToLinkedIn: 'Auf LinkedIn teilen',
      copiedForLinkedIn: 'Text kopiert! LinkedIn wird geöffnet...',
      pollInstructions: 'Füge deine Umfrage auf LinkedIn hinzu:',
      pollStep1: 'Füge den kopierten Text in den Post ein',
      pollStep2: 'Klicke auf das "Umfrage" Symbol (Balkendiagramm) in der Toolbar',
      pollStep3: 'Füge deine Umfrage-Frage und Optionen hinzu',
    },
    // Blocks
    blocks: {
      POLL: 'Umfrage-Kern',
      CHALLENGE: 'Validierungs-Herausforderung',
      TITLE: 'Post-Titel',
      CTA: 'Call-to-Action',
      HASHTAG: 'Hashtags',
      DURATION: 'Laufzeit',
      CUSTOM: 'Custom Text',
      DIVIDER: 'Trenner',
      MENTION: '@Mention',
      NUMBER: 'Zahlen',
      SCHEDULE: 'Termin',
    },
    // Feedback
    feedback: {
      title: 'Feedback',
      bugReport: 'Bug melden',
      idea: 'Idee',
      describeBug: 'Beschreibe den Bug...',
      describeIdea: 'Beschreibe deine Idee...',
      emailOptional: 'E-Mail (optional, für Rückfragen)',
      submit: 'Absenden',
      thanks: 'Danke für dein Feedback!',
      willContact: 'Wir melden uns bei dir.',
      sent: 'Feedback gesendet!',
      sendFailed: 'Feedback konnte nicht gesendet werden',
    },
    // Common
    common: {
      textCopied: 'Text kopiert!',
      loading: 'Laden...',
    },
    // Warnings
    warnings: {
      postTooLong: 'Post überschreitet LinkedIn-Limit',
      pollQuestionTooLong: 'Poll-Frage zu lang',
      pollOptionTooLong: 'Poll-Option zu lang',
    },
  },
};

// ============================================
// BLOCKS CONFIGURATION
// ============================================
export const BLOCKS = {
  POLL: { name: 'Umfrage-Kern', icon: BarChart3, req: true },
  CHALLENGE: { name: 'Validierungs-Herausforderung', icon: FlaskConical, req: false },
  TITLE: { name: 'Post-Titel', icon: Type, req: false },
  CTA: { name: 'Call-to-Action', icon: MessageSquare, req: false },
  HASHTAG: { name: 'Hashtags', icon: Hash, req: false },
  DURATION: { name: 'Laufzeit', icon: Timer, req: false },
  CUSTOM: { name: 'Custom Text', icon: PlusCircle, req: false },
  DIVIDER: { name: 'Trenner', icon: Minus, req: false },
  MENTION: { name: '@Mention', icon: AtSign, req: false },
  NUMBER: { name: 'Zahlen', icon: Bold, req: false },
  SCHEDULE: { name: 'Termin', icon: Calendar, req: false }
};

// ============================================
// INPUT VALIDATION LIMITS
// ============================================
export const INPUT_LIMITS = {
  TITLE: 150,
  CHALLENGE: 2000,
  POLL_QUESTION: LINKEDIN_LIMITS.POLL_QUESTION,
  POLL_OPTION: LINKEDIN_LIMITS.POLL_OPTION,
  CTA: 200,
  HASHTAG: 300,
  CUSTOM: 1000,
  MENTION: 100,
  NUMBER: 200,
};

export const DUR_LABELS = { '1day': '24H', '3days': '3 TAGE', '1week': '1 WOCHE' };
