import { LINKEDIN_LIMITS } from '../lib/postCompiler';

export const INPUT_LIMITS = {
  TITLE: 150,
  CHALLENGE: 2000,
  POLL_QUESTION: LINKEDIN_LIMITS.POLL_QUESTION,
  POLL_OPTION: LINKEDIN_LIMITS.POLL_OPTION,
  CTA: 200,
  HASHTAG: 300,
  CUSTOM: 1000,
  MENTION: 100,
  NUMBER: 200,
};
